-- 1. profiles 테이블에 role 컬럼 추가 (없다면)
alter table public.profiles 
add column if not exists role text default 'user';

-- 2. allowed_members 테이블 생성 (이미 존재하면 건너뜀)
create table if not exists public.allowed_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  affiliation text,
  -- society 컬럼이 아래 alter문으로 추가되므로 여기서는 생략 가능하나, 신규 생성을 위해 남겨둠
  society text, 
  note text
);

-- [중요] 기존 테이블이 있을 경우를 대비해 society 컬럼을 명시적으로 추가
alter table public.allowed_members 
add column if not exists society text;

-- 3. RLS 활성화
alter table public.allowed_members enable row level security;

-- 4. 정책 설정 (기존 정책이 있다면 삭제 후 재생성)
drop policy if exists "Enable all access for admins" on public.allowed_members;
drop policy if exists "Enable read access for authenticated users" on public.allowed_members;

-- 관리자(role='admin')는 모든 권한 허용
create policy "Enable all access for admins" on public.allowed_members
  for all using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
  );

-- 로그인한 모든 사용자는 조회(Select) 가능 (인증 로직용)
create policy "Enable read access for authenticated users" on public.allowed_members
  for select
  to authenticated
  using (true);

-- 5. 이메일 인덱스 생성
create index if not exists allowed_members_email_idx on public.allowed_members (email);

-- [옵션] 현재 사용자를 관리자로 지정하려면 아래 주석을 해제하고 이메일을 입력해서 실행하세요.
-- update public.profiles set role = 'admin' where email = 'kimbi.kirams@gmail.com';
