-- Table: public.allowed_members
-- Description: Whitelist for user registration approval.
-- Managed By: Master SQL Definition (sql_query/create_allowed_members.sql)

-- 1. Clean up existing table and policies
DROP TABLE IF EXISTS public.allowed_members CASCADE;

-- 2. Create Table
CREATE TABLE public.allowed_members (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Member Information
    name text,
    email text unique,
    affiliation text,
    department text, -- [NEW] 소속 부서
    classification text, -- [RENAMED] role -> classification (직종/구분)
    society text, -- 관련 학회 코드
    note text -- 비고
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.allowed_members ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies

-- Policy 1: Admins have full access (Select, Insert, Update, Delete)
CREATE POLICY "Enable all access for admins" on public.allowed_members
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.is_admin = true
    )
  );

-- Policy 2: Authenticated users can read (for verification logic)
CREATE POLICY "Enable read access for authenticated users" on public.allowed_members
  FOR SELECT
  TO authenticated
  USING (true);

-- 5. Create Indexes for performance
CREATE INDEX idx_allowed_members_email ON public.allowed_members(email);

-- 6. Comment on Table
COMMENT ON TABLE public.allowed_members IS '회원 가입 승인 허용 목록 (Whitelist)';
COMMENT ON COLUMN public.allowed_members.classification IS '직종 구분 (예: 전공의, 전문의, 기사, 간호사 등)';
